### ISSUE TITLE
Curseforge Download Workaround not opening Browser and not detecting manually downloaded mods

### ISSUE THREAD

**Issue by NightHammer1000** [flathub/com.atlauncher.ATLauncher#21]
The Workaround for Downloading Curseforge Modpacks does not work as intended.

Clicking the Button to download blocked Mods does not open the Browser.
If you download by copying the Link, the Downloaded Mod is not detected as downloaded.

**Comment by Doomsdayrs** [comment]
Thank you for the report. I will look into this as soon as possible

**Comment by NightHammer1000** [comment]
Thank you guys for finding a relatively comfortable workaround to the bullshit curseforge pulled.

**Comment by Doomsdayrs** [comment]
> Thank you guys for finding a relatively comfortable workaround to the bullshit curseforge pulled.

Can you provide an example modpack?

**Comment by Doomsdayrs** [comment]
I was unable to replicate this issue with my installation.

The steps I have performed are as following:
1. Click open
2. Notice browser opens, download begins
3. Return to ATLauncher, click "Open Folder"
4. Move the downloaded mod into the folder from Downloads.
5. Refocus on ATLauncher, File has been noticed.

![image](https://user-images.githubusercontent.com/38189170/172492832-01c47f50-e088-4c8c-a023-c8bb927327b7.png)

**Comment by NightHammer1000** [comment]
This has to be a Steam Deck specific Issue then. I'll try to get the console output tomorrow.

**Comment by Doomsdayrs** [comment]
For the other issue, in regards to the browser not opening.

What browser do you have?
What distro are you using?

**Comment by Doomsdayrs** [comment]
> This has to be a Steam Deck specific Issue then. I'll try to get the console output tomorrow.

Intriguing, Is there a browser installed on your steamdeck?

**Comment by Doomsdayrs** [comment]
> This has to be a Steam Deck specific Issue then. I'll try to get the console output tomorrow.

Thank you for the logs!

**Comment by NightHammer1000** [comment]
Okay. Strange.
It started working again today, and I am unable to replicate the Problem at all.
Guess we can close this here. I'll write this up to general SteamOS wonkyness.

Other Suggestion:
I have seen other flatpak Applications doing it: Adding the Permission to look inside the user's Download Folder to skip the Part of moving the files.

**Comment by Stuferus** [comment]
got atm7 yesterday with atlauncher.. this has been fully automatic for me.. it moved the fails automaticly after download.. im on linux mint 20.3 - if there was a way around to opening the browser (use of wget in the background? or curl?) i would be impressd and happy :)

**Comment by NightHammer1000** [comment]
PolyMC did it that way and got basically Cease and Desisted by Curseforge for breaking ToS. They have since removed the Workaround. So probably not happening.

**Comment by NightHammer1000** [comment]
This can be closed. It was indeed a Issue with flatpak on the Steam Deck itself. Everything works as intendet now.
