### ISSUE TITLE
xdg-download should be read-only to avoid Sandbox escape

### ISSUE THREAD

**Issue by Charadon** [flathub/com.atlauncher.ATLauncher#62]
In theory, a malicious mod could infect any file in the Downloads folder, and if a user runs it, would result in infection.

**Comment by Doomsdayrs** [comment]
The problem currently, is that ATLauncher [here](https://github.com/ATLauncher/ATLauncher/blob/157d465a2199415c56f8ab8eefc083c23c0125b2/src/main/java/com/atlauncher/workers/InstanceInstaller.java#L763) uses a move operation.

**Comment by Doomsdayrs** [comment]
Completed with fb6da911edacdf5c178cc790a8c1c503fd94e47f 2 days ago! Sorry for not closing this!
